# Generated by Django 4.2.3 on 2023-11-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_question_answer_is_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="question_answer",
            name="Question",
            field=models.CharField(default="질문", max_length=200),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="Answer",
            field=models.CharField(default="답변", max_length=200),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="Date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="Keywords",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="Links",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="user_key",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
